services:
  telegram-bot-app:
    build: .
    image: telegram-bot-app
    container_name: telegram-bot-app
    restart: unless-stopped
    mem_limit: 512m   
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
